# Generated by Django 5.0.4 on 2024-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('specialty', models.CharField(choices=[('psychologist', 'Psychologist'), ('coach', 'Coach'), ('doctor', 'Doctor'), ('therapist', 'Therapist'), ('counselor', 'Counselor'), ('psychiatrist', 'Psychiatrist'), ('nutritionist', 'Nutritionist')], max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
            ],
        ),
    ]
